// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3KvjaBWqGZYeyXuRLs7I8WOWM3PvS-wM',
    appId: '1:986946743750:web:594a63a99d6a44b4a056c7',
    messagingSenderId: '986946743750',
    projectId: 'food-panda-selling-app',
    authDomain: 'food-panda-selling-app.firebaseapp.com',
    storageBucket: 'food-panda-selling-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa6vwupFbJ3LsYnD9NK70DGqqcnM3kkaE',
    appId: '1:986946743750:android:cf1b58b1e0f9d365a056c7',
    messagingSenderId: '986946743750',
    projectId: 'food-panda-selling-app',
    storageBucket: 'food-panda-selling-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyOuTwSU5xSBKr3ik-RtiVm6ZygGWTt6s',
    appId: '1:986946743750:ios:21f9237af39ca82fa056c7',
    messagingSenderId: '986946743750',
    projectId: 'food-panda-selling-app',
    storageBucket: 'food-panda-selling-app.appspot.com',
    iosBundleId: 'com.example.foodpandaSellersApp',
  );
}
